image: microsoft/dotnet:1.0.0-rc2-core
before_script:
  - apt-get update
  - apt-get install -y uuidgen unzip
stages:
  - build
build:
  stage: build
  script:
    - bash build.sh --quiet verify
  artifacts:
    paths:
      - src/*/bin/Debug/*.nupkg
